-- MySQL Script generated by MySQL Workbench
-- Wed Jul  7 22:08:11 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema minha-audocao
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `minha-audocao` ;

-- -----------------------------------------------------
-- Schema minha-audocao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `minha-audocao` DEFAULT CHARACTER SET utf8 ;
USE `minha-audocao` ;


-- -----------------------------------------------------
-- Table `minha-audocao`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `minha-audocao`.`users` ;

CREATE TABLE IF NOT EXISTS `minha-audocao`.`users` (
  `username` VARCHAR(128) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `enabled` TINYINT NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minha-audocao`.`authorities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `minha-audocao`.`authorities` ;

CREATE TABLE IF NOT EXISTS `minha-audocao`.`authorities` (
  `authority` VARCHAR(128) NOT NULL,
  `username` VARCHAR(128) NOT NULL,
  INDEX `fk_authorities_users1_idx` (`username` ASC) VISIBLE,
  UNIQUE INDEX `authorities_unique` (`username` ASC, `authority` ASC) VISIBLE,
  CONSTRAINT `fk_authorities_users1`
    FOREIGN KEY (`username`)
    REFERENCES `minha-audocao`.`users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
