version: "3.9"

services:
    db:
        image: minhaudocao/db
        restart: always
        container_name: minhaudocao-db
        ports:
            - "3306:3306"

networks:
    default:
        external: true
        name: minhaudocao_network